use ITI

------------------- >>> Variables <<< -------------------
-- *** Local Variables

-- to declare a variable
declare @x int

-- to asign a value to variable 
------ way#1
set @x = 10

-- to display a variable
select @x


------ way#2
declare @x int
select @x = 10
select @x

------ way#3 case:1
declare @x int
-- @x var ل id = 3 بتاع الطالب اللي age بتاع value ال asign بتعرض لا ده احنا بنselect مبقتش جملة
select @x = St_Age from Student where St_Id = 3
select @x

------		 case:2
declare @x int
-- اي اللي هيحصل؟ id = 999 علي قيمة مش موجودة يعني انا اصلا معنديش where طب افرض انا عملت
-- NULL هيحتفظ باخر قيمة كانت جواه ويطبعهالك او لو مكنش جواه اي قيمة يطبعvariable ال
select @x = St_Age from Student where St_Id = 999
select @x

------		 case:3
declare @x int
-- هيشيل اخر قيمة بس var ال where علي حاجة بترجع اكتر من قيمة او معملتش where طب افرض انا عملت
select @x = St_Age from Student where St_Address = 'Alex'
select @x

-- SQL في array اللي رجعت طب ازاي واحنا اصلا معندناش values طب ياخي انا رخمة وعايزة احتفظ بكل ال
-- @t >> table(variable) name,	x >> table(variable) اللي جوه column اسم ال
declare @t table(x int) -- ex: @t table( x int, @y varchar(50),... ) عادي col ممكن ترجع اكثر من
-- insert based on select ونقلبها table من نوع var نعمل 
-- memory موجود في table بس طبعا ده
insert into @t
select St_Age from Student where St_Address = 'Alex'
select * from @t


-- if i want to display valus from diff columns
declare @age int, @name varchar(50)
select @age = St_Age, @name = St_Fname from Student where St_Id = 10
select @age, @name

------ way#4
declare @x int

--  id = 7 في نفس الوقت بابديت الاسم للطالب اللي update, select ده كانه بقي 
-- @x var احطها في dept_id قيمة select و
update Student set St_Fname = 'ali', @x = dept_id
where St_Id = 7

select @x



-- declare and assign in the same line
declare @y int = 100
select @y

-- variable والناتج بنحطه في ال AVG(Salary) بتحسب subquery هنا بستخدم
declare @y int
select @y = (select AVG(Salary) from Instructor)
select @y


-- شوية فبدل ما نحط القيمة ب ايدينا dynamic كانت بتاخد قيمة ثابتة ممكن نخلي الموضوع top() فاكرة ال
-- ترجع عدد صفوف مختلف top فكل ما قيمة المتغير تتغير ال top ونباصيه لل declare var لا ن 
declare @count int
set @count = 4
select top(@count)*
from Student

-- وده مينفعش @tab => string هيصطدم انreplace بس لما يجي يعمل select * from student كأني عايزة اقوله
-- table لازم بعدها from لان 
declare @col varchar(20) = '*' , @tab varchar(20) = 'student'
select @col from @tab

select 'select * from student' -- res >> 'select * from student'

-- لو ينفع query وتحوله ل string بتاخد execute() اسمها keyword في بقي عندنا
execute('select * from student')

declare @col varchar(20) = '*' , @tab varchar(20) = 'student'
-- dynamic query فيبقي معانا concatenation هنا مع شوية  execute() فممكن بقي استخدم
-- معينة وهكذا columns ممكن نحدد star(*) وبدل instructor تبقي student بدل values لاني ممكن اغير ال
execute('select ' + @col + 'from ' + @tab)

------------------------------------------------------------------------------------------

-- *** Global Variables
select @@SERVERNAME
select @@VERSION

update Student
set St_Age +=1

-- @@ROWCOUNT >> a SQL Server system variable that returns the number of rows affected
--				(inserted, updated, or deleted) by the last executed Transact-SQL statement
select @@ROWCOUNT


/*
	@@ERROR >> is a system function used for error handling. 
	It returns the error number of the last executed T-SQL statement within the current session.

	Return Value: @@ERROR returns an INTEGER value.
		0:				  If the previous T-SQL statement executed successfully without any errors.
		Non-zero integer: If the previous statement encountered an error, 
						  @@ERROR returns the specific error number associated with that error.
*/
select @@ERROR


/*
	@@IDENTITY >> returns the last identity value generated by an INSERT, SELECT INTO, or bulk copy
				  statement within the current session and scope, 
				  useful for getting the ID of a newly added row,
*/
select @@IDENTITY